name: micromachines
version: 1.0.0
author: Danny Hendrix
description: MicroMachines
homepage: http://www.dannyhendrix.com
sdk: ">=2.0.0"
dev_dependencies:
  build_runner: "^0.8.2"
  build_web_compilers: ">=0.3.6 <0.5.0"
dependencies:
  logging: ">=0.11.3"
  gameutils:
    path: ../subpackages/gameutils
  dashboard:
    path: ../subpackages/dashboard
  preloader:
    path: ../subpackages/preloader
  renderlayer:
    path: ../subpackages/renderlayer
  object2map:
    path: ../subpackages/object2map
  webgl:
    path: ../subpackages/webgl

  gamelevelcontrol:
    path: ../subpackages/gamelevelcontrol
