name: micromachines
version: 1.0.0
author: Danny Hendrix
description: MicroMachines
homepage: http://www.dannyhendrix.com
environment:
  sdk: '>=2.1.0 <3.0.0'
dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
dependencies:
  logging: ">=0.11.3"
  gameutils:
    path: ../subpackages/gameutils
  dashboard:
    path: ../subpackages/dashboard
  preloader:
    path: ../subpackages/preloader
  renderlayer:
    path: ../subpackages/renderlayer
  webgl:
    path: ../subpackages/webgl
