name: gamedefinitions
version: 1.0.0
author: Danny Hendrix
description: RaceGame definitions and settings
homepage: http://www.dannyhendrix.com
environment:
  sdk: '>=2.1.0 <3.0.0'
dev_dependencies:
  build_runner: ^1.7.2
dependencies:
  logging: ">=0.11.3"
  dependencyinjection:
    path: ../../subpackages/dependencyinjection
  gameutils:
    path: ../../subpackages/gameutils
