name: gamelogic
version: 1.0.0
author: Danny Hendrix
description: RaceGame logic
homepage: http://www.dannyhendrix.com
environment:
  sdk: '>=2.1.0 <3.0.0'
dev_dependencies:
  build_runner: ^1.7.2
dependencies:
  logging: ">=0.11.3"
  test: ^1.16.8
  gameutils:
    path: ../../subpackages/gameutils
  dependencyinjection:
    path: ../../subpackages/dependencyinjection
  gamedefinitions:
    path: ../gamedefinitions