name: renderlayer
version: 0.0.1
author: Danny Hendrix
description: Makes it easier to work with the canvasElement/ctx (2d).

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.7.2
  build_web_compilers: ^2.7.1
  test: ^1.5.1
