@startuml
rectangle {
rectangle gameutils.gameloop as gameloop.dart
rectangle gameutils.gametime as gametime.dart
rectangle gameutils.gfx as gfx.dart
rectangle gameutils.math as math.dart
rectangle gameutils.settings as settings.dart
}
gameloop.dart  -->  dart_html
gfx.dart  -->  dart_html
gfx.dart  -->  package_renderlayer_renderlayer.dart
math.dart  -->  dart_math
settings.dart  -->  dart_html
settings.dart  -->  dart_convert
@enduml
